name: Amazon Affiliate Bot
on:
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - env:
          # Sirf yeh 3 basic secrets chahiye
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py
      - name: Update History
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add history.json || exit 0
          git commit -m "sync history" || exit 0
          git push
